#
###################################
# Site wide configuration
####################################
#
title: lazycat
email:
description: A Programmer.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: lazycat
  avatar: logo.png
  job: "A Programmer"
  bio: "Cleverness is a gift, kindness is a choice."
  email: chenxiawei@gmail.com
  disqus-shortname: spiritbook
  weibo: #username

